export const WIDGET_WIDTH = 2400;
export const WIDGET_HEIGHT = 1860;

export const WIDGET_SPACING = 16;

export const WIDGET_INSPECTOR_DETAILS_WIDTH = 464;

export const WIDGET_COLOR_GOLD = "#F4BF2A";
export const WIDGET_COLOR_GRAY = "#808080";
export const WIDGET_COLOR_RED = "#AA2409";
export const WIDGET_COLOR_RED_LIGHT = "#b23300";
export const WIDGET_COLOR_TRANSMOG = "#D980FF";
export const WIDGET_COLOR_STAT = "#ffffff";
export const WIDGET_COLOR_SET_EQUIPPED = "#FFFF98";
export const WIDGET_COLOR_SET_UNEQUIPPED = "#808080";

export const WIDGET_COLOR_QUALITY_ARTIFACT = "#e5cc80";
export const WIDGET_COLOR_QUALITY_AZERITE = WIDGET_COLOR_QUALITY_ARTIFACT;
export const WIDGET_COLOR_QUALITY_HEIRLOOM = "#00ccff";
export const WIDGET_COLOR_QUALITY_LEGENDARY = "#ff8000";
export const WIDGET_COLOR_QUALITY_EPIC = "#c600ff";
export const WIDGET_COLOR_QUALITY_RARE = "#0081ff";
export const WIDGET_COLOR_QUALITY_UNCOMMON = "#1eff00";
export const WIDGET_COLOR_QUALITY_COMMON = "#ffffff";
export const WIDGET_COLOR_QUALITY_POOR = "#9d9d9d";

export const WIDGET_QUALITY_COLORS = {
  artifact: WIDGET_COLOR_QUALITY_ARTIFACT,
  azerite: WIDGET_COLOR_QUALITY_AZERITE,
  heirloom: WIDGET_COLOR_QUALITY_HEIRLOOM,
  legendary: WIDGET_COLOR_QUALITY_LEGENDARY,
  epic: WIDGET_COLOR_QUALITY_EPIC,
  rare: WIDGET_COLOR_QUALITY_RARE,
  uncommon: WIDGET_COLOR_QUALITY_UNCOMMON,
  common: WIDGET_COLOR_QUALITY_COMMON,
  poor: WIDGET_COLOR_QUALITY_POOR
}

export const WIDGET_COLOR_CLASS_DEATHKNIGHT = "#c41e3b";
export const WIDGET_COLOR_CLASS_DEMONHUNTER = "#a330c9";
export const WIDGET_COLOR_CLASS_DRUID = "#ff7c0a";
export const WIDGET_COLOR_CLASS_EVOKER = "#33937f";
export const WIDGET_COLOR_CLASS_HUNTER = "#aad372";
export const WIDGET_COLOR_CLASS_MAGE = "#68ccef";
export const WIDGET_COLOR_CLASS_MONK = "#00ffba";
export const WIDGET_COLOR_CLASS_PALADIN = "#f48cba";
export const WIDGET_COLOR_CLASS_PRIEST = "#f0ebe0";
export const WIDGET_COLOR_CLASS_ROGUE = "#fff468";
export const WIDGET_COLOR_CLASS_SHAMAN = "#2359ff";
export const WIDGET_COLOR_CLASS_WARLOCK = "#9382c9";
export const WIDGET_COLOR_CLASS_WARRIOR = "#c69b6d";

export const WIDGET_CLASS_COLORS = {
  deathknight: WIDGET_COLOR_CLASS_DEATHKNIGHT,
  demonhunter: WIDGET_COLOR_CLASS_DEMONHUNTER,
  druid: WIDGET_COLOR_CLASS_DRUID,
  evoker: WIDGET_COLOR_CLASS_EVOKER,
  hunter: WIDGET_COLOR_CLASS_HUNTER,
  mage: WIDGET_COLOR_CLASS_MAGE,
  monk: WIDGET_COLOR_CLASS_MONK,
  paladin: WIDGET_COLOR_CLASS_PALADIN,
  priest: WIDGET_COLOR_CLASS_PRIEST,
  rogue: WIDGET_COLOR_CLASS_ROGUE,
  shaman: WIDGET_COLOR_CLASS_SHAMAN,
  warlock: WIDGET_COLOR_CLASS_WARLOCK,
  warrior: WIDGET_COLOR_CLASS_WARRIOR
}

export const WIDGET_COLUMN_Y_OFFSET = 756;